In [3]:
import torch

print(f"PyTorch version: {torch.__version__}")

PyTorch version: 1.12.1


In [6]:
import torch as tr
a=tr.tensor([1,2,3]) #create 1d tensor
b=tr.tensor([[2,3,5],[4,5,6]])
result=a+b
result1=result+2
sinx=tr.sin(result1)
print(result)
print(result1)
print(sinx)

tensor([[3, 5, 8],
        [5, 7, 9]])
tensor([[ 5,  7, 10],
        [ 7,  9, 11]])
tensor([[-0.9589,  0.6570, -0.5440],
        [ 0.6570,  0.4121, -1.0000]])


In [17]:
import torch as tr
x = tr.tensor([2.0], requires_grad=True)

# Define a simple function
y = x**4

# Perform a backward pass to compute gradients
y.backward()
# Access the gradient of x
print(x.grad)
x.grad.zero_()

# Perform the second operation
z = 3*x**2

# Compute gradients for the second operation
z.backward()

# Access the gradient of x after the second operation
print("Gradient after the second operation:", x.grad)  # Output: tensor([2.])
# Inside torch.no_grad(), gradients are not tracked
with tr.no_grad():
    # Perform the second operation
    z =3*x**2

# Gradients are not tracked for the second operation, so x.grad remains unchanged
print("Gradient after the second operation:", x.grad)  # Output: tensor([4.])

tensor([32.])
Gradient after the second operation: tensor([12.])
Gradient after the second operation: tensor([12.])


In [29]:
import torch as tr
x = tr.tensor([2.0], requires_grad=True)

# Define a simple function
y = x**4

# Perform a backward pass to compute gradients
y.backward()
print(x.grad)

y.backward()
print(x.grad)

tensor([32.])


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [30]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([2.0], requires_grad=True)

# Perform the first operation
y = x**2

# Compute the first-order gradient
grad_first_order = torch.autograd.grad(y, x, create_graph=True)[0]

# Compute the second-order gradient (Hessian matrix)
grad_second_order = torch.autograd.grad(grad_first_order, x)[0]

# Access the first-order gradient
print("First-order gradient:", grad_first_order.item())  # Output: 4.0

# Access the second-order gradient (Hessian matrix)
print("Second-order gradient (Hessian matrix):", grad_second_order.item())  # 

First-order gradient: 4.0
Second-order gradient (Hessian matrix): 2.0


In [31]:
import torch

# Create a tensor with requires_grad=True
x = torch.tensor([2.0], requires_grad=True)

# Perform the first operation
y = x**2

# Compute gradients for the first operation (first derivative)
y.backward()

# Access the gradient of x after the first operation
print("Gradient (1st derivative):", x.grad)  # Output: tensor([4.])

# Perform the backward pass again for the second derivative
y.backward()

# Access the gradient of x after the second operation (second derivative)
print("Gradient (2nd derivative):", x.grad)  # Output: tensor([8.])


Gradient (1st derivative): tensor([4.])


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.